@Restaurants.API_HostAddress = https://localhost:7087

GET {{Restaurants.API_HostAddress}}/api/restaurants/


###

Patch {{Restaurants.API_HostAddress}}/api/restaurants/6
Content-Type: application/json
{
  "Name" : "sjdklsjf",
  "Description" : "jdksljdfksldlsl"

}

###
