// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Data;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20251223210556_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TaskManagement.Core.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Design REST endpoints",
                            DueDate = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Design API",
                            Priority = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Business rules & validation",
                            DueDate = new DateTime(2025, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Implement Service Layer",
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "xUnit + Moq",
                            DueDate = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Write Unit Tests",
                            Priority = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "EF Core + SQLite",
                            DueDate = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Setup SQLite",
                            Priority = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "How to run & test",
                            DueDate = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Prepare README",
                            Priority = 1,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
